### ISSUE TITLE
请求引用

### ISSUE THREAD

**Issue by drinktoomuchsax** [Yuzhe-Fu/EE332#1]
学姐/学长好，请求在[SUSTech-EE-Course-Hero](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero)里引用你的项目以及引用你的仓库内容：)

**Comment by Yuzhe-Fu** [comment]
ok 一切顺利！


---- 回复的原邮件 ----
发件人 Cao Zhengyang ***@***.***> 发送日期 2024年03月18日 23:40 收件人 Yuzhe-Fu/EE332 ***@***.***> 抄送人 Subscribed ***@***.***> 主题 [Yuzhe-Fu/EE332] 请求引用 (Issue #1)  

学姐/学长好，请求在SUSTech-EE-Course-Hero里引用你的项目以及引用你的仓库内容：)

**Comment by drinktoomuchsax** [comment]
respect!
